# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17xMoqAhZZ78VYpt0I-Sc4_qa61NCgo-c
"""

from google.colab import files
import pandas as pd

# Subir archivo desde tu PC (selecciona games.csv)
uploaded = files.upload()

# Cargar dataset
df = pd.read_csv("games.csv")

# Ver primeras filas
df.head()

# --- Exploración ---
df.info()

# Total de partidas
total_partidas = len(df)

# Conteo de partidas clasificadas y no clasificadas
clasificadas = df["rated"].value_counts()

# Estados de victoria
victorias = df["victory_status"].value_counts()

# Ganadores
ganadores = df["winner"].value_counts()

# Promedio de rating
promedio_white = df["white_rating"].mean()
promedio_black = df["black_rating"].mean()

# Promedio de movimientos por partida
promedio_turnos = df["turns"].mean()

# Aperturas más comunes (Top 10)
aperturas = df["opening_name"].value_counts().head(10).reset_index()
aperturas.columns = ["Apertura", "Cantidad"]

# Resumen general
resumen = pd.DataFrame({
    "Métrica": [
        "Total de partidas",
        "Promedio rating blancas",
        "Promedio rating negras",
        "Promedio de movimientos"
    ],
    "Valor": [
        total_partidas,
        round(promedio_white, 2),
        round(promedio_black, 2),
        round(promedio_turnos, 2)
    ]
})

# --- Estilos tipo Excel ---
def estilo_excel(df):
    return (df.style
              .set_table_styles([
                  {"selector": "th", "props": [("background-color", "#4472C4"),
                                               ("color", "white"),
                                               ("font-weight", "bold"),
                                               ("text-align", "center")]},
                  {"selector": "td", "props": [("text-align", "center")]}
              ])
              .highlight_max(color="#92D050", axis=0)
              .highlight_min(color="#F4B084", axis=0)
              .set_properties(**{"border": "1px solid black", "padding": "5px"}))

# Mostrar tablas con diseño bonito
print("📌 Resumen general:")
display(estilo_excel(resumen))

print("♟️ Partidas clasificadas vs no clasificadas:")
display(estilo_excel(clasificadas.reset_index().rename(columns={"index": "Tipo", "rated": "Cantidad"})))

print("🏆 Estados de victoria:")
display(estilo_excel(victorias.reset_index().rename(columns={"index": "Estado de victoria", "victory_status": "Cantidad"})))

print("👑 Ganadores:")
display(estilo_excel(ganadores.reset_index().rename(columns={"index": "Ganador", "winner": "Cantidad"})))

print("📖 Top 10 aperturas más comunes:")
display(estilo_excel(aperturas))