# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17xMoqAhZZ78VYpt0I-Sc4_qa61NCgo-c
"""

from google.colab import files
import pandas as pd

# Subir archivo desde tu PC (selecciona covid_19_data.csv)
uploaded = files.upload()

# Cargar dataset
df = pd.read_csv("covid_19_data.csv")

# Ver primeras filas
df.head()

# --- Exploración ---
df.info()

# Total de registros
# Total de registros
total_registros = len(df)

# Casos confirmados, muertes y recuperados
total_confirmados = df["Confirmed"].sum()
total_muertes = df["Deaths"].sum()
total_recuperados = df["Recovered"].sum()

# Por región (los 10 primeros)
casos_por_region = (
    df.groupby("Region")[["Confirmed", "Deaths", "Recovered"]]
      .sum()
      .sort_values(by="Confirmed", ascending=False)
      .head(10)
      .reset_index()
)

# Resumen general
resumen = pd.DataFrame({
    "Métrica": [
        "Total de registros",
        "Total casos confirmados",
        "Total muertes",
        "Total recuperados"
    ],
    "Valor": [
        total_registros,
        total_confirmados,
        total_muertes,
        total_recuperados
    ]
})

# --- Estilos tipo Excel ---
def estilo_excel(df):
    return (df.style
              .set_table_styles([
                  {"selector": "th", "props": [("background-color", "#4472C4"),
                                               ("color", "white"),
                                               ("font-weight", "bold"),
                                               ("text-align", "center")]},
                  {"selector": "td", "props": [("text-align", "center")]}
              ])
              .highlight_max(color="#92D050", axis=0)
              .highlight_min(color="#F4B084", axis=0)
              .set_properties(**{"border": "1px solid black", "padding": "5px"}))

# Mostrar tablas con diseño bonito
print("📌 Resumen general:")
display(estilo_excel(resumen))

print("🌍 Top 10 regiones con más casos confirmados:")
display(estilo_excel(casos_por_region))