# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17xMoqAhZZ78VYpt0I-Sc4_qa61NCgo-c
"""

from google.colab import files
import pandas as pd

# Subir archivo desde tu PC (te pedirá seleccionarlo)
uploaded = files.upload()

# Luego lo cargas en un DataFrame
df = pd.read_csv("ncr_ride_bookings.csv")  # ajusta el nombre exacto

# Total de viajes
total_viajes = len(df)

# Estado de las reservas (confirmadas, canceladas, incompletas, etc.)
estado_reservas = df["Booking Status"].value_counts().reset_index()
estado_reservas.columns = ["Estado de la reserva", "Cantidad"]

# Tipos de vehículo
tipos_vehiculo = df["Vehicle Type"].value_counts().reset_index()
tipos_vehiculo.columns = ["Tipo de vehículo", "Cantidad"]

# Métodos de pago
metodos_pago = df["Payment Method"].value_counts().reset_index()
metodos_pago.columns = ["Método de pago", "Cantidad"]

# Promedios
promedio_valor = df["Booking Value"].mean()
promedio_distancia = df["Ride Distance"].mean()
promedio_rating_driver = df["Driver Ratings"].mean()
promedio_rating_cliente = df["Customer Rating"].mean()

# Resumen en tabla
resumen = pd.DataFrame({
    "Métrica": [
        "Total de viajes",
        "Promedio valor de viaje",
        "Promedio distancia (km)",
        "Promedio rating conductor",
        "Promedio rating cliente"
    ],
    "Valor": [
        total_viajes,
        round(promedio_valor, 2),
        round(promedio_distancia, 2),
        round(promedio_rating_driver, 2),
        round(promedio_rating_cliente, 2)
    ]
})

# --- Estilos tipo Excel ---
def estilo_excel(df):
    return (df.style
              .set_table_styles([
                  {"selector": "th", "props": [("background-color", "#4472C4"),
                                               ("color", "white"),
                                               ("font-weight", "bold"),
                                               ("text-align", "center")]},
                  {"selector": "td", "props": [("text-align", "center")]}
              ])
              .highlight_max(color="#92D050", axis=0)
              .highlight_min(color="#F4B084", axis=0)
              .set_properties(**{"border": "1px solid black", "padding": "5px"}))

# Mostrar tablas con diseño bonito
print("📊 Estado de las reservas:")
display(estilo_excel(estado_reservas))

print("🚗 Tipos de vehículo:")
display(estilo_excel(tipos_vehiculo))

print("💳 Métodos de pago:")
display(estilo_excel(metodos_pago))

print("📌 Resumen general:")
display(estilo_excel(resumen))